version: "3.9"

services:
  server:
    build: ./server
    container_name: server
    expose:
      - "8080"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - server
